### ISSUE TITLE
Spring Autowire error when using the annotation eu.hinsch.spring.boot.actuator.metric.ExecutionMetric on methods of a bean

### ISSUE THREAD

**Issue by jgoldhammer** [lukashinsch/spring-boot-execution-metric#10]
Hi,

when using the annotation on public methods of a bean, autowiring this bean into another bean fails...

```
@Service
public class Bean{

@ExecutionMetric(value = "dql-executeQuery")
public void doing(){

...
}
}
```

Stacktrace:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [xxx.Bean] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        ... 71 common frames omitted

```

Environment:
Spring Boot 1.3.1
Spring 4.2.4

Any ideas what is wrong here?

**Comment by jgoldhammer** [comment]
Ok, got it. the bean implements an interface and I had to put the annotations on the interface...
Do you have an explanation for this?

**Comment by lukashinsch** [comment]
Hi,

this has to do with how spring AOP handles proxies that are needed to handle the aspects. By default, if a bean implements an interface jdk-proxies are created, where only interface methods are proxied. Without interfaces the more powerful CGLIB-proxies are created. In your case, the proxy only implements the interface and therefore is not an instance of the bean class itself and cannot be autowired. Moving the annotations to the interface method worked for me only so far as to make the autowired work, but the aspect is never executed. 
What did work for me was to force spring to create CGLIB-proxies even for beans implementing an interface. Try something like this on a config class:

```
@EnableAspectJAutoProxy(proxyTargetClass=true)
@Configuration
```

Hope that clears the issue up.

Best regards
Lukas
